remote_theme: ToiletCommander/academic-website-template

title: Yunhao Cao
email: 
description: Homepage of Yunhao Cao @ UC Berkeley
baseurl: ""
url: ""

# Footer info
affiliation: >
  量子饼干<br />
  Quantum Cookie<br />
  <a href="http://rail.eecs.berkeley.edu/" target="_blank">RAIL Lab</a><br />
  <a href="https://roar.berkeley.edu/" target="_blank">ROAR Lab</a><br />

location: >
  University of California, Berkeley<br/>
  Berkeley, CA 94704

contact: >
  <a href="https://github.com/toiletCommander/blog/issues/1">Contact Me!</a>

nav_pages: 
  - name: about
  - name: publications
  - name: talks
  - name: research


include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: 
  - 'jekyll/scholar'
  - 'jekyll-remote-theme'

scholar:
  last_name: Cao
  first_name: [Yunhao]

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile